=head1 Massad's Henge Methods

Massad's Henge is accessible via the URL C</massadshenge>.

The list of methods below represents changes and additions to the methods that all L<Buildings> share.


=head2 list_planets (session_id, building_id, [ star_id ] )

Provides the list of the planets around a given star.

{
	"status" : { ... },
	"planets" : [
		{
		"id" : "id-goes-here",
		"name" : "Earth"
		},
		...
	]
}

=head3 session_d

A session id.

=head3 building_id

The unique id of the building.

=head3 star_id

Optionally pass in a star id. Defaults to the star that the building is built on. See L<Map/"search_stars"> to see how you can get a star id by name.

=head2 view_planet_incoming ( session_id, building_id, planet_id, [ page_number ] )

Shows you all the foreign ships that are incoming. However, the list is filtered by the stealth of the ship vs the level of the Massads Henge. The formula is:

500 * Henge Level >= Ship Stealth

If your Henge exceeds the Ship's Stealth, then you'll see it incoming. Otherwise you won't.

{
	"ships" : [
		{
			"id" : "id-goes-here",
			"name" : "CS3",
			"type_human" : "Cargo Ship",
			"type" : "cargo_ship",
			"date_arrives" : "02 01 2010 10:08:33 +0600",
			"can_recall" : "0",
			"can_scuttle" : "0",
			"from" : {
				"id" : "id-goes-here",
				"name" : "Earth",
				"empire" : {
					"id" : "id-goes-here",
					"name" : "Earthlings"
				}
			}
		},
		...
	],
	"number_of_ships" : 13,
	"status" : { ... }
}

The C<from> block is only included if

600 * Henge Level >= Ship Stealth

=head3 session_id

A session id.

=head3 building_id

The unique id of the massads henge.

=head3 planet_id

The unique id of a planet you want to view incoming ships for. Note that this must be a planet id and not a body id. It won't work for an asteroid for example. Also, the planet must be in range. You get 10 star map units per level of the Henge.

=head3 page_number

Defaults to page 1. Shows 25 at a time.

=head2 view_ships_orbiting ( session_id, building_id, planet_id, [ page_number ])

Shows you all the foreign ships that are orbiting this planet. However, the list is filtered by the stealth of the ship vs the level of the Massads Henge. The formula is:

500 * Massads Henge Level >= Ship Stealth

If your Massads Henge exceeds the Ship's Stealth, then you'll see it orbiting. Otherwise you won't.

{
	"ships" : [
		{
			"id" : "id-goes-here",
			"name" : "SS3",
			"type" : "spy_shuttle",
			"type_human" : "Spy Shuttle",
			"date_arrived" : "02 01 2010 10:08:33 +0600",
			"from" : {
				"id" : "id-goes-here",
				"name" : "Mars",
				"empire" : {
					"id" : "id-goes-here",
					"name" : "Martians"
				}
			}
		},
		{
			"id" : "id-goes-here",
			"name" : "F3",
			"type" : "fighter",
			"type_human" : "Fighter",
			"from" : {
				"id" : "id-goes-here",
				"name" : "Earth",
				"empire" : {
					"id" : "id-goes-here",
					"name" : "Earthlings"
				}
			}
		},
		...
	],
	"number_of_ships" : 13,
	"status" : { ... }
}

The C<from> block is only included if

600 * Massads Henge Level >= Ship Stealth

=head3 session_id

A session id.

=head3 building_id

The unique id of the massads henge.

=head3 planet_id

The unique id of a planet you want to view orbiting ships for. Note that this must be a planet id and not a body id. It won't work for an asteroid for example. Also, the planet must be in range. You get 10 star map units per level of the Henge.

=head3 page_number

Defaults to page 1. Shows 25 at a time.


=cut
